version: "2.0"

services:
    zalenium:
        image: "dosel/zalenium"
        container_name: zalenium
        hostname: zalenium
        tty: true
        volumes:
            - /tmp/videos:/home/seluser/videos
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 4444:4444
        command: >
            start --desiredContainers 2
                  --maxDockerSeleniumContainers 8
                  --screenWidth 1024 --screenHeight 768
                  --timeZone "Europe/Berlin"
                  --videoRecordingEnabled true
                  --sauceLabsEnabled false
                  --browserStackEnabled false
                  --testingBotEnabled false
                  --startTunnel false
        environment:
            - HOST_UID
            - HOST_GID
            - SAUCE_USERNAME
            - SAUCE_ACCESS_KEY
            - BROWSER_STACK_USER
            - BROWSER_STACK_KEY
            - TESTINGBOT_KEY
            - TESTINGBOT_SECRET
            - PULL_SELENIUM_IMAGE=true
